/**:
  ros__parameters:
    offline_frames_per_step: 4
    topic_imu: /mavros/imu/data
    acc_ratio: false
    lidars: ["hkust_conti"]
    hkust_conti:
      topic_lidar: /radar_raw_message
      lidar_type: HkustContinental
      scan_line: 16
      blind: 0.0
      max_range: 30.0
      min_z: -1.0
      q_bl: [1.0,  0.0,  0.0,  0.0]
      t_bl: [0.0, 0.0, 0.05]

      w_pt: 0.01  # point weight
      w_vel: 0.01 # velocity weight # too high go up
      ransac:
        mode: "3d"
        sample_size: 5
        outlier_prob: 0.05
        success_prob: 0.995
        inlier_threshold: 0.2
        min_static_points: 30
    lidar_time_offset: 0.1

    knot_hz: 20 # 10, 20
    if_lidar_only: false

    point_filter_num: 1
    nn_thresh: 1.0
    coeff_cov: 3.0
    num_nn: 5
    plane_thresh : 0.05

    ds_lm_voxel: 0.05 # for mapping
    cube_len: 1000.0

    cov_P0: 0.02
    cov_RCP_pos_old: 0.1
    cov_RCP_ort_old: 0.1
    cov_RCP_pos_new: 1.0
    cov_RCP_ort_new: 1.0
    std_sys_pos: 0.1
    std_sys_ort: 0.1
    cov_acc: [1.0,1.0,1.0]
    cov_gyro: [0.01,0.01,0.01]
    cov_ba: [0.01, 0.01, 0.01]
    cov_bg: [0.01, 0.01, 0.01]
    cov_grav: 1.0
    n_iter: 5
    num_points_upd: 5000

    min_cov_thresh: 0.0001 # minimum uncertainty threshold
    max_cov_thresh: 0.0005 # maximum uncertainty threshold
    min_cov_bound: 0.01
    max_cov_bound: 0.05
    min_plane_cov_thresh: 0.0015
    max_plane_cov_thresh: 0.003
    min_plane_cov_bound: 0.0075
    max_plane_cov_bound: 0.0125

    radar_noise:
      range_std: 0.2
      azimuth_std: 0.5
      elevation_std: 0.5

    result_file_path: "evaluate/hkust_seq2.txt"
    result_file_path_ns: "evaluate/hkust_seq2_ns.txt"
    gt_path: "/root/data/hkust/Sequence_2.txt"
    gt_time_unit: "s" # "ns", "s", "ms"
